name: Java Linter
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  check_changes:
    runs-on: [ubuntu-latest]
    name: Check changes in javascript app
    outputs:
      status: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            app_javascript/**
