name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: JavaScript Lint
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx