name: Lint

on:
  push:
    paths-ignore:
      - 'app_javascript/app_js/node_modules/**'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Python Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run flake8
        uses: py-actions/flake8@v2
  delivery:
    runs-on: ubuntu-latest
    name: Markdown Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Run mdl
        uses: actionshub/markdownlint@main