name: Markdown Lint

on: [push]

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Markdown Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Run mdl
        uses: actionshub/markdownlint@main
        with:
          filesToIgnoreRegex: |
            "devops/terraform\\/.*"
            "devops/ansible\\/.*"
            "devops/app_javascript/app_js/node_modules\\/.*"
