name: CI python

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  check_changes:
    runs-on: [ubuntu-latest]
    name: Check changes in python app
    outputs:
      status: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changed files
        id: changed
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            app_python/**
  build:
    needs: check_changes
    runs-on: [ubuntu-latest]
    if: needs.check_changes.outputs.status == 'true'
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_lab2:latest