name: Snyk Python
on: push

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: snyk/actions/setup@master
     - name: Snyk Test
       run: snyk test --sarif-file-output=snyk-sarif.json
       continue-on-error: true       
       env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    